### ISSUE TITLE
Feature: Custom background

### ISSUE THREAD

**Issue by Merudo** [rtakehara/5e-Framework#18]
**Is your feature request related to a problem? Please describe.**
Backgrounds other than the Acolyte are not available in the SRD, precluding them from being included in the framework.

However, the rules allow for "custom" backgrounds (2 skills + any 2 languages or tool proficiencies).

**Describe the solution you'd like**
At character creation, the player should be able to build their own "custom" background.

**Describe alternatives you've considered**
An easier way to add backgrounds to the character creation wizard.

**Comment by rtakehara** [comment]
I like this idea, also when a background that isn't acolyte is added to the settings and has a feature with it's name, but doesn't have the proper macros is detected, the "custom" input could also show up, same goes for classes (skills, saves, and other proficiencies) and races (attributes, languages and others)

**Comment by rtakehara** [comment]
Made this feature for background and races, and it will be available hopefully soon in 2.5.1.

Races will prompt for:
- attribute bonuses (or penalties)
- languages (lists with any number of entries)
- size
- speed (land, fly, swim, climb and burrow)
- sight

Races will prompt for:
- 2 skills
- languages (lists with any number of entries, including zero)
- tools (lists with any number of entries, including zero)
- list of equipment (only 1 of each, quantities can be changed on character sheet later)
- Gold Pieces

Didn't made one for classes since classes are a little more complex, but if this works without problems I will make one for classes and subclasses too
