### ISSUE TITLE
Links no longer working v2.5

### ISSUE THREAD

**Issue by tomcgable** [rtakehara/5e-Framework#23]
**Describe the bug**
Created links inside a notebook no longer center and focus on Pins.
It worked in the v2.4.7 of the framework.

**To Reproduce**
1. Placed Token ....Converted to pin via "GM Menu" named it "1" (without the quotes)
2. Placed 2nd Token .....Converted it to a new Notebook from the create notebook menu item.
3. Created a new title and edited it with the following
  [Test] (pin "1@01.Start")
  without the space between ] and the ( 
4. Saved the notebook and reloaded it
5. Changed my view on the map to test the link
6. Clicked the link in the notebook nothing happens no error in the chat window or via java popup
7. Reviewed my code from previous working iteration of the framework (v.2.4.7)
**Expected behavior**
I expected the map to change focus and center on the pin.

**Desktop:**
 - OS: Windows 10
 - Maptools Version 1.7.0

**Comment by rtakehara** [comment]
I see the problem, maptool 1.7 introduced a function (`MarkdownToHTML()`) so I changed my code to use it for performance reasons, but I somehow managed to break it in the process. It will be fixed in next version.

Also, I personally think using `[text](pin "TokenName@MapName")` is limiting (if you change the map name you have to change every mention of it) so I decided to make it link to just pins on that map (so just `[text](token "TokenName")`) and a new code for just for maps (`[text](map "MapName")`) would be more flexible, what do you thing?

**Comment by tomcgable** [comment]
I concur the the linking system [text](pin "TokenName@MapName") is limiting should you change the map name.
Thanks for the update. I tried everything i could
