### ISSUE TITLE
Weapon Proficiency always applied to Attack Bonus

### ISSUE THREAD

**Issue by francespower** [rtakehara/5e-Framework#25]
**Description**
When setting up a weapon on the character sheet, the Atk Bonus field always adds the character's proficiency bonus regardless of whether the character is proficient in the weapon. 

Example: A druid with 18 Strength (+4) and +2 proficiency is wielding a warhammer. Their base attack roll without proficiency is 1d20+4. With proficiency, it's 1d20+6. When the "is proficient" checkbox is unchecked, the attack bonus remains at +6 on the character sheet anyway, but pops up with a star to indicate that there's no proficiency. 

Screenshot showing this example: 
![image](https://user-images.githubusercontent.com/69366543/89685545-8a175600-d8ca-11ea-9054-cb3f34a2dd1e.png)

**To Reproduce**

1. Create a character token. 
2. Open the Character Sheet. 
3. Click on "Attacks and Spellcasting" to add a weapon or attack to the character. 
4. Add an attack roll formula. 
5. Ensure checkbox that says, "Is Proficient," is unchecked. 
6. Click "OK"
7. Check the character sheet. 

**Expected behavior**
The character sheet should show an attack bonus of +4, not +6, because there is no proficiency to add to the strength modifier since the character is not proficient with a warhammer. 

**Software versions:**
 - OS: Windows 10
 - MapTool: 1.7.0
 - 5e Framework 2.5

**Additional context**
This issue was brought up to me by another person in my group running a different computer, and I later replicated it on my machine in versions 2.4.7 and 2.5.

**Comment by rtakehara** [comment]
Oh, ops, I think this was kinda intentional at one point, my reasoning was why add an attack if you are not proficient with it? But yeah, that's a bad idea and I was just finding excuses to be lazy.

The fix is done and will be released soon-ish

Also included tooltips to help creating custom attacks, other as a secondary damage type in case of weird spell effects (no impact on game, just to make it feel more like a customization and less like a replacement for lack of features), spell as attack types (also to keep consistency, this will also change the roll box color to purple as all spell attacks are, not real changes on mechanics) and default values that help players understand how it is meant to be used
